# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v22
      with:
        servers: >
          [
            {
              "id": "anypoint-exchange-v3",
              "username": "~~~Client~~~",
              "password": "0ecef233b4934d01bb3718acbb34b8fa~?~81a33116561d4CD5BB76cd778Cb3CfDe"
              }
            },
            {
              "id": "MuleRepository",
              "username": "timdai-training",
              "password": "Training@2021"
              }
            },
            {
              "id": "exchange-server",
              "username": "~~~Client~~~",
              "password": "0ecef233b4934d01bb3718acbb34b8fa~?~81a33116561d4CD5BB76cd778Cb3CfDe"
              }
            }  
          ]
        plugin_groups: >
          [
            "org.mule.tools"
          ]          
        repositories: >
          [
            {
              "id": "some-repository",
              "name": "some-repository-name",
              "url": "http://some.repository.url",
              "releases": {
                "enabled": "true",
                "updatePolicy": "always",
                "checksumPolicy": "fail"
              },
              "snapshots": {
                "enabled": "false",
                "updatePolicy": "always",
                "checksumPolicy": "fail"
              }
            }
          ]
        plugin_repositories: >
          [
            {
              "id": "some-plugin-repository",
              "name": "some-plugin-repository-name",
              "url": "http://some.plugin.repository.url",
              "releases": {
                "enabled": "true"
              },
              "snapshots": {
                "enabled": "false"
              }
            }
          ]

        mirrors: >
          [
            {
              "id": "nexus",
              "mirrorOf": "!my-org-snapshots,*",
              "url": "http://redacted/nexus/content/groups/public"
            }
          ]
        profiles: >
          [
            {
              "id": "foo.profile",
              "name": "foo.profile",
              "url": "http://foo.bar.profile",
              "properties": {
                "foo": "property-1",
                "bar": "property-2"
              }
            }
          ]

        proxies: >
          [
            {
              "id": "foo-proxy",
              "active": "true",
              "protocol": "http",
              "host": "https://proxy.example.com",
              "port": "443",
              "username": "foo",
              "password": "bar",
              "nonProxyHosts": "noproxy1.example.com|noproxy2.example.com"
            }
          ]
        active_profiles: >
          [
            "some-profile"
          ]
        output_file: .m2/settings.xml
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
