name: build_deploy_reusable.yml
on:
  workflow_call:
    inputs:
      CLOUDHUB_ENVIRONMENT:
        required: true
        type: string
      GITHUB_ENVIRONMENT:
        required: true
        type: string                    
      CLOUDHUB_WORKERS:
        required: true
        type: string
      CLOUDHUB_WORKER_TYPE:
        required: true
        type: string                
      CLOUDHUB_REGION:
        required: true
        type: string                
      HTTP_PORT:
        required: true
        type: string       
      MULE_VERSION:
        required: true
        type: string         
    secrets:
      ANYPOINT_PLATFORM_CLIENT_ID:
        required: true
      ANYPOINT_PLATFORM_CLIENT_SECRET:
        required: true
      MAVEN_SETTINGS:
        required: true
      CONNECTED_APP_CLIENT_ID:
        required: true
      CONNECTED_APP_CLIENT_SECRET:
        required: true
        
jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.GITHUB_ENVIRONMENT }}    
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"

    - uses: actions/checkout@v4.1.2
      with:
        ref: ${{ github.event.ref}}        
        
    - name: Set up JDK 8
      uses: actions/setup-java@v4.2.1
      with:
        distribution: 'temurin'
        cache: 'maven'
        java-version: 8
        server-id: github

    - name: Populate settings.xml
      run: |
        mkdir -p /home/runner/.m2/
        touch /home/runner/.m2/settings.xml
        echo "${{ secrets.MAVEN_SETTINGS }}" > /home/runner/.m2/settings.xml

    - name: JOB settings DETAILS
      run: |
        cat /home/runner/.m2/settings.xml

    - name: Print mvn version
      run: |
        mvn -version        

    - name: Deploy for ${{ github.event.ref }} branch
      run: |
        mvn -U -V -e -B -DskipTests deploy --file pom.xml -DmuleDeploy -DmuleVersion=4.6.0 -Dconnected.app.client_id=0ecef233b4934d01bb3718acbb34b8fa -Dconnected.app.client_secret=81a33116561d4CD5BB76cd778Cb3CfDe -Denvironment=DEV -DworkerType=MICRO -Dworkers=1 -Dregion=ap-southeast-2 -Dhttp.port=8091 -Danypoint.platform.client_id=2528b12293bb4ec4badc0af331309655 -Danypoint.platform.client_secret=DB8424fB944745E198dDE27E283b864f
#        mvn -U -V -e -B -DskipTests deploy --file pom.xml -DmuleDeploy -DmuleVersion=${{ inputs.MULE_VERSION}} -Dconnected.app.client_id=${{ secrets.CONNECTED_APP_CLIENT_ID}} -Dconnected.app.client_secret=${{ secrets.CONNECTED_APP_CLIENT_SECRET}} -Denvironment=${{ inputs.CLOUDHUB_ENVIRONMENT}} -DworkerType=${{ inputs.CLOUDHUB_WORKER_TYPE}} -Dworkers=${{ inputs.CLOUDHUB_WORKERS}} -Dregion=${{ inputs.CLOUDHUB_REGION}} -Dhttp.port=${{ inputs.HTTP_PORT}} -Danypoint.platform.client_id=${{ secrets.ANYPOINT_PLATFORM_CLIENT_ID}} -Danypoint.platform.client_secret=${{ secrets.ANYPOINT_PLATFORM_CLIENT_SECRET}}     
        
