name: build_deploy_reusable.yml
on:
  workflow_call:
    inputs:
      CLOUDHUB_ENVIRONMENT:
        required: true
        type: string
      GITHUB_ENVIRONMENT:
        required: true
        type: string                    
      CLOUDHUB_WORKERS:
        required: true
        type: string
      CLOUDHUB_WORKER_TYPE:
        required: true
        type: string                
      CLOUDHUB_REGION:
        required: true
        type: string                
      HTTP_PRIVATE_PORT:
        required: true
        type: string                        
    secrets:
      CLOUDHUB_USERNAME:
        required: true    
      CLOUDHUB_PASSWORD:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.GITHUB_ENVIRONMENT }}    
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"

    - uses: actions/checkout@v4.1.2
      with:
        ref: ${{ github.event.ref}}        
        
    - name: Set up JDK 8
      uses: actions/setup-java@v4.2.1
      with:
        distribution: 'temurin'
        cache: 'maven'
        java-version: 8
        server-id: github

    - uses: s4u/maven-settings-action@v3.0.0
      with:
        servers: '[{"id": "mule-connected-app", "username": "${{ secrets.CLOUDHUB_USERNAME}}", "password": "${{ secrets.CLOUDHUB_USERNAME }}"}]'

    - name: JOB settings DETAILS
      run: |
        cat /home/runner/.m2/settings.xml
        
