name: ci_cd_pipeline.yml

# Run on new release creation or when manually triggered
on:
  workflow_dispatch:
#    inputs:
#      releaseType:
#        description: 'Where to release (staging or prod)?'     
#        required: true
#        default: 'staging'
env:
  ## Cloudhub Properties
  CLOUDHUB_WORKERS: 1
  CLOUDHUB_WORKER_TYPE: MICRO
  CLOUDHUB_REGION: ap-southeast-2  

  ## API specific 
  HTTP_PRIVATE_PORT: 8091  

jobs:
  DEV:
    uses: ./.github/workflows/build_deploy_reusable.yml
    with:
      CLOUDHUB_ENVIRONMENT: "DEV"
      GITHUB_ENVIRONMENT: "DEV"      
      CLOUDHUB_WORKERS: ${{ env.CLOUDHUB_WORKERS}}
      CLOUDHUB_WORKER_TYPE: ${{ env.CLOUDHUB_WORKER_TYPE}}
      CLOUDHUB_REGION: ${{ evn.CLOUDHUB_REGION}}
      HTTP_PRIVATE_PORT: "8091"
    secrets:
      CLOUDHUB_USERNAME: ${{ secrets.CLOUDHUB_USERNAME }}       
      CLOUDHUB_PASSWORD : ${{ secrets.CLOUDHUB_PASSWORD }}

  SIT:
    if: github.event.inputs.releaseType == 'SIT'  
    needs: [DEV]
    uses: ./.github/workflows/build_deploy_reusable.yml
    with:
      CLOUDHUB_ENVIRONMENT: "SIT"
      GITHUB_ENVIRONMENT: "SIT"      
      CLOUDHUB_WORKERS: ${{ env.CLOUDHUB_WORKERS}}
      CLOUDHUB_WORKER_TYPE: ${{ env.CLOUDHUB_WORKER_TYPE}}
      CLOUDHUB_REGION: ${{ env.CLOUDHUB_REGION}}
      HTTP_PRIVATE_PORT: "8091"
    secrets:
      CLOUDHUB_USERNAME: ${{ secrets.CLOUDHUB_USERNAME }}        
      CLOUDHUB_PASSWORD : ${{ secrets.CLOUDHUB_PASSWORD }}

  PROD:
    if: github.event.inputs.releaseType == 'PROD'  
    needs: [SIT]
    uses: ./.github/workflows/build_deploy_reusable.yml
    with:
      CLOUDHUB_ENVIRONMENT: "PROD"
      GITHUB_ENVIRONMENT: "PROD"      
      CLOUDHUB_WORKERS: ${{ env.CLOUDHUB_WORKERS}}
      CLOUDHUB_WORKER_TYPE: ${{ env.CLOUDHUB_WORKER_TYPE}}
      CLOUDHUB_REGION: ${{ env.CLOUDHUB_REGION}}
      HTTP_PRIVATE_PORT: "8091"
    secrets:
      CLOUDHUB_USERNAME: ${{ secrets.CLOUDHUB_USERNAME }}        
      CLOUDHUB_PASSWORD : ${{ secrets.CLOUDHUB_PASSWORD }}
