name: ci_cd_pipeline.yml

# Run on new release creation or when manually triggered
on:
  workflow_dispatch:
#    inputs:
#      releaseType:
#        description: 'Where to release (staging or prod)?'     
#        required: true
#        default: 'staging'
env:
  ## Cloudhub Properties
  CLOUDHUB_WORKERS: 1
  CLOUDHUB_WORKER_TYPE: MICRO
  CLOUDHUB_REGION: ap-southeast-2  

  ## API specific 
  HTTP_PORT: 8091  

jobs:
  DEV:
    uses: ./.github/workflows/build_deploy_reusable.yml
    with:
      CLOUDHUB_ENVIRONMENT: "DEV"
      GITHUB_ENVIRONMENT: "DEV"      
      CLOUDHUB_WORKERS: 1
      CLOUDHUB_WORKER_TYPE: MICRO
      CLOUDHUB_REGION: ap-southeast-2
      HTTP_PORT: "8091"
      MULE_VERSION: "4.6"
    secrets:
      ANYPOINT_PLATFORM_CLIENT_ID: ${{ secrets.ANYPOINT_PLATFORM_CLIENT_ID }}       
      ANYPOINT_PLATFORM_CLIENT_SECRET: ${{ secrets.ANYPOINT_PLATFORM_CLIENT_SECRET }}
      MAVEN_SETTINGS: ${{ secrets.MAVEN_SETTINGS }}
      CONNECTED_APP_CLIENT_ID: ${{ secrets.CONNECTED_APP_CLIENT_ID }}
      CONNECTED_APP_CLIENT_SECRET: ${{ secrets.CONNECTED_APP_CLIENT_SECRET }}
