# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: TEST

on:
  workflow_dispatch:

env:
  ## Cloudhub Properties
  CLOUDHUB_REGION: ap-southeast-2  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: test
      run: echo ${{ env.CLOUDHUB_REGION }}
